---
- hosts: controller
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: overwrite hostname
      hostname: 
        name: "{{ ansible_host }}"
    - name: create cert directory
      file:
        path: /cluster-certs
        state: directory
    - name: create kubeconfig directory
      file:
        path: /kubeconfig
        state: directory
    - name: Copy CA files
      copy:
        src: '{{item}}'
        dest: '/cluster-certs'
        owner: ec2-user
        group: ec2-user
        mode: 0644
      loop:
        - "{{ playbook_dir }}/../pki/pem/ca.pem"
        - "{{ playbook_dir }}/../pki/pem/ca-key.pem"
        - "{{ playbook_dir }}/../pki/pem/api.pem"
        - "{{ playbook_dir }}/../pki/pem/api-key.pem"
        - "{{ playbook_dir }}/../pki/pem/service-account.pem"
        - "{{ playbook_dir }}/../pki/pem/service-account-key.pem"
    - name: Copy kubeconfig files
      copy:
        src: '{{item}}'
        dest: '/kubeconfig'
        owner: ec2-user
        group: ec2-user
        mode: 0644
      loop:
        - "{{ playbook_dir }}/../kubecfg/admin.kubeconfig"
        - "{{ playbook_dir }}/../kubecfg/kube-scheduler.kubeconfig"
        - "{{ playbook_dir }}/../kubecfg/kube-controller-manager.kubeconfig"
        - "{{ playbook_dir }}/../kubecfg/encryption-config.yaml"