---
- hosts: worker
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: overwrite hostname
      ansible.builtin.hostname: 
        name: "{{ ansible_host }}"
    - name: create cert directory
      file:
        path: /home/ec2-user/cluster-certs
        state: directory
    - name: create kubeconfig directory
      file:
        path: /home/ec2-user/kubeconfig
        state: directory
    - name: create kubeyaml directory
      file:
        path: /home/ec2-user/kubeyaml
        state: directory
    - name: create /home/ec2-user/download folder
      file:
        path: /home/ec2-user/download
        state: directory
    - name: create /home/ec2-user/containerd folder
      file:
        path: /home/ec2-user/containerd
        state: directory
    - name: create additional folders
      file:
        path: '{{ item }}'
        state: directory
      loop:
        - "/etc/cni/net.d"
        - "/etc/containerd"
        - "/opt/cni/bin"
        - "/var/lib/kubelet"
        - "/var/lib/kube-proxy"
        - "/var/lib/kubernetes"
        - "/var/run/kubernetes"
    - name: Copy public CA files
      copy:
        src: '{{item}}'
        dest: '/home/ec2-user/cluster-certs'
        owner: ec2-user
        group: ec2-user
        mode: 644
      loop:
        - "{{ playbook_dir }}/../pki/pem/ca.pem"
        - "{{ playbook_dir }}/../pki/pem/{{ inventory_hostname }}.pem"
    - name: Copy private CA files
      copy:
        src: "{{ playbook_dir }}/../pki/pem/{{ inventory_hostname }}-key.pem"
        dest: '/home/ec2-user/cluster-certs'
        owner: ec2-user
        group: ec2-user
        mode: 600
    - name: Copy kubeconfig files
      copy:
        src: '{{item}}'
        dest: '/home/ec2-user/kubeconfig'
        owner: ec2-user
        group: ec2-user
        mode: 0644
      loop:
        - "{{ playbook_dir }}/../kubecfg/{{ inventory_hostname }}.kubeconfig"
        - "{{ playbook_dir }}/../kubecfg/kube-proxy.kubeconfig"
    - name: Copy kubeyaml files
      copy:
        src: '{{item}}'
        dest: '/home/ec2-user/kubeyaml'
        owner: ec2-user
        group: ec2-user
        mode: 0644
      loop:
        - "{{ playbook_dir }}/../kubeyaml/kubelet-config-{{ inventory_hostname }}.yaml"
        - "{{ playbook_dir }}/../kubeyaml/kube-proxy-config.yaml"
    - name: Copy network config files
      copy:
        src: '{{item}}'
        dest: '/etc/cni/net.d'
        owner: ec2-user
        group: ec2-user
        mode: 0644
      loop:
        - "{{ playbook_dir }}/../network-conf/10-bridge-{{ inventory_hostname }}.conf"
        - "{{ playbook_dir }}/../network-conf/99-loopback.conf"
    - name: Copy containerd files
      copy:
        src: '{{ playbook_dir }}/../containerd/config.toml'
        dest: '/etc/containerd/'
        owner: ec2-user
        group: ec2-user
        mode: 0644
    - name: Copy service files from remote
      copy:
        src: "{{ item }}"
        dest: '/etc/systemd/system/'
        owner: root
        group: root
        mode: 0644
      loop:
        - "{{ playbook_dir }}/../services/kube-proxy.service"
        - "{{ playbook_dir }}/../services/kubelet-{{ inventory_hostname }}.service"
        - "{{ playbook_dir }}/../services/containerd.service"