---
- hosts: controller
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Install nginx
      command: amazon-linux-extras install nginx1 -y
    - name: Copy nginx file from remote
      copy:
        src: "{{ playbook_dir }}/../nginx/health-check.conf"
        dest: '/etc/nginx/conf.d/'
        owner: root
        group: root
        mode: 0644
    - name: Start nginx server
      ansible.builtin.systemd:
        state: started
        daemon_reload: yes
        name: nginx