---
- hosts: worker
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: overwrite hostname
      hostname: 
        name: "{{ ansible_host }}"
    - name: create cert directory
      file:
        path: /home/ec2-user/cluster-certs
        state: directory
    - name: create kubeconfig directory
      file:
        path: /home/ec2-user/kubeconfig
        state: directory
    - name: Copy public CA files
      copy:
        src: '{{item}}'
        dest: '/home/ec2-user/cluster-certs'
        owner: ec2-user
        group: ec2-user
        mode: 644
      loop:
        - "{{ playbook_dir }}/../pki/pem/ca.pem"
        - "{{ playbook_dir }}/../pki/pem/{{ inventory_hostname }}.pem"
        - "{{ playbook_dir }}/../pki/pem/{{ inventory_hostname }}-key.pem"
    - name: Copy private CA files
      copy:
        src: '{{item}}'
        dest: '/home/ec2-user/cluster-certs'
        owner: ec2-user
        group: ec2-user
        mode: 600
      loop:
        - "{{ playbook_dir }}/../pki/pem/{{ inventory_hostname }}-key.pem"
    - name: Copy kubeconfig files
      copy:
        src: '{{item}}'
        dest: '/home/ec2-user/kubeconfig'
        owner: ec2-user
        group: ec2-user
        mode: 0644
      loop:
        - "{{ playbook_dir }}/../kubecfg/{{ inventory_hostname }}.kubeconfig"
        - "{{ playbook_dir }}/../kubecfg/kube-proxy.kubeconfig"