---
- hosts: worker
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: overwrite hostname
      hostname: 
        name: "{{ ansible_host }}"
    - name: create cert directory
      file:
        path: /cluster-certs
        state: directory
    - name: Copy CA files
      copy:
        src: '{{item}}'
        dest: '/cluster-certs'
        owner: ec2-user
        group: ec2-user
        mode: 0644
      loop:
        - ./pki/pem/ca.pem
        - "./pki/pem/{{ ansible_host }}.pem"
        - "./pki/pem/{{ ansible_host }}-key.pem"